# Generated by Django 5.1.15 on 2026-05-15 23:26

import apps.tramites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DNI', 'DNI'), ('TITULO_SEC', 'Título Secundario'), ('CERT_MED', 'Certificado médico'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to=apps.tramites.models.documento_path)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'documento',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERT_REGULAR', 'Certificado de alumno regular'), ('CERT_MATERIAS', 'Certificado de materias aprobadas'), ('ANALITICO', 'Analítico parcial'), ('TITULO', 'Solicitud de título'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('codigo_qr_verificacion', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'tramite',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
