# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='revisado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMINISTRATIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='administrativo',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMINISTRATIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
