# Generated by Django 5.1.15 on 2026-05-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('REGULAR', 'Regular'), ('LIBRE', 'Libre'), ('BAJA', 'Baja')], default='ACTIVA', max_length=10)),
            ],
            options={
                'db_table': 'inscripcion_cursada',
            },
        ),
        migrations.CreateModel(
            name='InscripcionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('AUSENTE', 'Ausente'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('BAJA', 'Baja')], default='INSCRIPTO', max_length=15)),
                ('codigo_comprobante', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'inscripcion_final',
            },
        ),
    ]
