# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncursada',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_cursada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcioncursada',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.comision'),
        ),
        migrations.AddField(
            model_name='inscripcionfinal',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_final', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionfinal',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.mesaexamen'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncursada',
            unique_together={('alumno', 'comision')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionfinal',
            unique_together={('alumno', 'mesa')},
        ),
    ]
