# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.comision'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.acta'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('comision', 'alumno', 'fecha_clase')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('acta', 'alumno')},
        ),
    ]
