# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=30)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Correlativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSADA', 'Para cursar (regularizada)'), ('FINAL', 'Para rendir final (aprobada)')], max_length=10)),
            ],
            options={
                'db_table': 'correlativa',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('regimen', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], default='CUATRIMESTRAL', max_length=15)),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'materia',
                'ordering': ['anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cupo', models.PositiveIntegerField(default=50)),
                ('cerrada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mesa_examen',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('inscripciones_abiertas', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'periodo_lectivo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('anio_vigencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_estudio',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=120)),
                ('cupo', models.PositiveIntegerField(default=40)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.aula')),
            ],
            options={
                'db_table': 'comision',
            },
        ),
    ]
