# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='profesores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'PROFESOR'}, related_name='comisiones_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correlativa',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='correlativa',
            name='requiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerida_por', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='comision',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='profesores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'PROFESOR'}, related_name='mesas_tribunal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comision',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academico.periodolectivo'),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='academico.planestudio'),
        ),
        migrations.AlterUniqueTogether(
            name='correlativa',
            unique_together={('materia', 'requiere', 'tipo')},
        ),
    ]
