# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=15)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('POSTULADO', 'Postulado'), ('PRESELECCIONADO', 'Preseleccionado'), ('RECHAZADO', 'Rechazado'), ('ACEPTADO', 'Aceptado')], default='POSTULADO', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'postulacion',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('RESIDENCIA', 'Residencia'), ('PASANTIA', 'Pasantía'), ('EMPLEO', 'Empleo')], max_length=15)),
                ('requisitos', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='bolsa.institucion')),
            ],
            options={
                'db_table': 'oferta',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
