# Generated by Django 5.1.15 on 2026-05-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='bolsa.oferta'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('alumno', 'oferta')},
        ),
    ]
